# configuration for log collection
# https://toml.io/en/v1.0.0#array-of-tables

[dynamodb]

[[dynamodb.package]]
source = "test1.log"
table = "test1-table"

[[dynamodb.package]]
source = "test2.log"
table = "test2-table"
